import type { LanguageProfile } from "../../types/liveDubbing";

export const SUPPORTED_LANGUAGES: LanguageProfile[] = [
  { code: "fa", nameEn: "Persian", nameFa: "فارسی", flagEmoji: "🇮🇷", isRtl: true },
  { code: "en", nameEn: "English", nameFa: "انگلیسی", flagEmoji: "🇺🇸" },
  { code: "ar", nameEn: "Arabic", nameFa: "عربی", flagEmoji: "🇸🇦", isRtl: true },
  { code: "de", nameEn: "German", nameFa: "آلمانی", flagEmoji: "🇩🇪" },
  { code: "fr", nameEn: "French", nameFa: "فرانسوی", flagEmoji: "🇫🇷" },
  { code: "es", nameEn: "Spanish", nameFa: "اسپانیایی", flagEmoji: "🇪🇸" },
  { code: "it", nameEn: "Italian", nameFa: "ایتالیایی", flagEmoji: "🇮🇹" },
  { code: "tr", nameEn: "Turkish", nameFa: "ترکی استانبولی", flagEmoji: "🇹🇷" },
  { code: "ru", nameEn: "Russian", nameFa: "روسی", flagEmoji: "🇷🇺" },
  { code: "zh", nameEn: "Chinese (Simplified)", nameFa: "چینی ساده", flagEmoji: "🇨🇳" },
  { code: "zh-TW", nameEn: "Chinese (Traditional)", nameFa: "چینی سنتی", flagEmoji: "🇹🇼" },
  { code: "ja", nameEn: "Japanese", nameFa: "ژاپنی", flagEmoji: "🇯🇵" },
  { code: "ko", nameEn: "Korean", nameFa: "کره‌ای", flagEmoji: "🇰🇷" },
  { code: "hi", nameEn: "Hindi", nameFa: "هندی", flagEmoji: "🇮🇳" },
  { code: "pt-BR", nameEn: "Portuguese (Brazil)", nameFa: "پرتغالی برزیل", flagEmoji: "🇧🇷" },
  { code: "pt-PT", nameEn: "Portuguese (Portugal)", nameFa: "پرتغالی پرتغال", flagEmoji: "🇵🇹" },
  { code: "nl", nameEn: "Dutch", nameFa: "هلندی", flagEmoji: "🇳🇱" },
  { code: "sv", nameEn: "Swedish", nameFa: "سوئدی", flagEmoji: "🇸🇪" },
  { code: "no", nameEn: "Norwegian", nameFa: "نروژی", flagEmoji: "🇳🇴" },
  { code: "da", nameEn: "Danish", nameFa: "دانمارکی", flagEmoji: "🇩🇰" },
  { code: "fi", nameEn: "Finnish", nameFa: "فنلاندی", flagEmoji: "🇫🇮" },
  { code: "pl", nameEn: "Polish", nameFa: "لهستانی", flagEmoji: "🇵🇱" },
  { code: "uk", nameEn: "Ukrainian", nameFa: "اوکراینی", flagEmoji: "🇺🇦" },
  { code: "el", nameEn: "Greek", nameFa: "یونانی", flagEmoji: "🇬🇷" },
  { code: "he", nameEn: "Hebrew", nameFa: "عبری", flagEmoji: "🇮🇱", isRtl: true },
  { code: "ur", nameEn: "Urdu", nameFa: "اردو", flagEmoji: "🇵🇰", isRtl: true },
  { code: "id", nameEn: "Indonesian", nameFa: "اندونزیایی", flagEmoji: "🇮🇩" },
  { code: "ms", nameEn: "Malay", nameFa: "مالایی", flagEmoji: "🇲🇾" },
  { code: "th", nameEn: "Thai", nameFa: "تایلندی", flagEmoji: "🇹🇭" },
  { code: "vi", nameEn: "Vietnamese", nameFa: "ویتنامی", flagEmoji: "🇻🇳" },
  { code: "cs", nameEn: "Czech", nameFa: "چکی", flagEmoji: "🇨🇿" },
  { code: "hu", nameEn: "Hungarian", nameFa: "مجاری", flagEmoji: "🇭🇺" },
  { code: "ro", nameEn: "Romanian", nameFa: "رومانیایی", flagEmoji: "🇷🇴" },
  { code: "sk", nameEn: "Slovak", nameFa: "اسلواکی", flagEmoji: "🇸🇰" },
  { code: "bg", nameEn: "Bulgarian", nameFa: "بلغاری", flagEmoji: "🇧🇬" },
  { code: "sr", nameEn: "Serbian", nameFa: "صربی", flagEmoji: "🇷🇸" },
  { code: "hr", nameEn: "Croatian", nameFa: "کرواتی", flagEmoji: "🇭🇷" },
  { code: "sl", nameEn: "Slovenian", nameFa: "اسلوونیایی", flagEmoji: "🇸🇮" },
  { code: "lt", nameEn: "Lithuanian", nameFa: "لیتوانیایی", flagEmoji: "🇱🇹" },
  { code: "lv", nameEn: "Latvian", nameFa: "لتونیایی", flagEmoji: "🇱🇻" },
  { code: "et", nameEn: "Estonian", nameFa: "استونیایی", flagEmoji: "🇪🇪" },
  { code: "hy", nameEn: "Armenian", nameFa: "ارمنی", flagEmoji: "🇦🇲" },
  { code: "ka", nameEn: "Georgian", nameFa: "گرجی", flagEmoji: "🇬🇪" },
  { code: "az", nameEn: "Azerbaijani", nameFa: "آذربایجانی", flagEmoji: "🇦🇿" },
  { code: "uz", nameEn: "Uzbek", nameFa: "ازبکی", flagEmoji: "🇺🇿" },
  { code: "kk", nameEn: "Kazakh", nameFa: "قزاقی", flagEmoji: "🇰🇿" },
  { code: "bn", nameEn: "Bengali", nameFa: "بنگالی", flagEmoji: "🇧🇩" },
  { code: "pa", nameEn: "Punjabi", nameFa: "پنجابی", flagEmoji: "🇮🇳" },
  { code: "ta", nameEn: "Tamil", nameFa: "تامیلی", flagEmoji: "🇮🇳" },
  { code: "te", nameEn: "Telugu", nameFa: "تلوگو", flagEmoji: "🇮🇳" },
  { code: "mr", nameEn: "Marathi", nameFa: "مراتی", flagEmoji: "🇮🇳" },
  { code: "gu", nameEn: "Gujarati", nameFa: "گجراتی", flagEmoji: "🇮🇳" },
  { code: "kn", nameEn: "Kannada", nameFa: "کانادایی", flagEmoji: "🇮🇳" },
  { code: "ml", nameEn: "Malayalam", nameFa: "مالایالم", flagEmoji: "🇮🇳" },
  { code: "my", nameEn: "Burmese", nameFa: "برمه‌ای", flagEmoji: "🇲🇲" },
  { code: "km", nameEn: "Khmer", nameFa: "خمر", flagEmoji: "🇰🇭" },
  { code: "lo", nameEn: "Lao", nameFa: "لائوسی", flagEmoji: "🇱🇦" },
  { code: "ne", nameEn: "Nepali", nameFa: "نپالی", flagEmoji: "🇳🇵" },
  { code: "si", nameEn: "Sinhala", nameFa: "سینهالی", flagEmoji: "🇱🇰" },
  { code: "fil", nameEn: "Filipino", nameFa: "فیلیپینی", flagEmoji: "🇵🇭" },
  { code: "sw", nameEn: "Swahili", nameFa: "سواحیلی", flagEmoji: "🇰🇪" },
  { code: "af", nameEn: "Afrikaans", nameFa: "آفریکانس", flagEmoji: "🇿🇦" },
  { code: "am", nameEn: "Amharic", nameFa: "امهری", flagEmoji: "🇪🇹" },
  { code: "ha", nameEn: "Hausa", nameFa: "هائوسا", flagEmoji: "🇳🇬" },
  { code: "is", nameEn: "Icelandic", nameFa: "ایسلندی", flagEmoji: "🇮🇸" },
  { code: "mk", nameEn: "Macedonian", nameFa: "مقدونی", flagEmoji: "🇲🇰" },
  { code: "mn", nameEn: "Mongolian", nameFa: "مغولی", flagEmoji: "🇲🇳" },
  { code: "sd", nameEn: "Sindhi", nameFa: "سندی", flagEmoji: "🇮🇳" },
  { code: "rw", nameEn: "Kinyarwanda", nameFa: "کینیارواندایی", flagEmoji: "🇷🇼" },
  { code: "zu", nameEn: "Zulu", nameFa: "زولو", flagEmoji: "🇿🇦" },
];
